HelloWorld64: HelloWorld64.o
	ld -o HelloWorld64 HelloWorld64.o
HelloWorld64.o: HelloWorld64.s
	as -o HelloWorld64.o HelloWorld64.s
HelloWorld32: HelloWorld32.o
	ld -o HelloWorld32 HelloWorld32.o
HelloWorld32.o: HelloWorld32.s
	as -o HelloWorld32.o HelloWorld32.s
Input64: Input64.o
	ld -o Input64 Input64.o
Input64.o: Input64.s
	as -o Input64.o Input64.s
Input32: Input32.o
	ld -o Input32 Input32.o
Input32.o: Input32.s
	as -o Input32.o Input32.s
BigToSmall64: BigToSmall64.o
	ld -o BigToSmall64 BigToSmall64.o
BigToSmall64.o: BigToSmall64.s
	as -o BigToSmall64.o BigToSmall64.s
BigToSmall32: BigToSmall32.o
	ld -o BigToSmall32 BigToSmall32.o
BigToSmall32.o: BigToSmall32.s
	as -o BigToSmall32.o BigToSmall32.s
Reverse32: Reverse32.o
	ld -o Reverse32 Reverse32.o
Reverse32.o: Reverse32.s
	as -o Reverse32.o Reverse32.s
Reverse64: Reverse64.o
	ld -o Reverse64 Reverse64.o
Reverse64.o: Reverse64.s
	as -o Reverse64.o Reverse64.s
