FindMin: FindMin.o
	ld -o FindMin FindMin.o
FindMin.o: FindMin.s
	as -o FindMin.o FindMin.s
FindMax: FindMax.o
	ld -o FindMax FindMax.o
FindMax.o: FindMax.s
	as -o FindMax.o FindMax.s
HexToBin: HexToBin.o
	ld -o HexToBin HexToBin.o
HexToBin.o: HexToBin.s
	as -o HexToBin.o HexToBin.s
Cezar: Cezar.o
	ld -o Cezar Cezar.o
Cezar.o: Cezar.s
	as -o Cezar.o Cezar.s
clean:
	rm -f FindMin FindMin.o	
	rm -f FindMax FindMax.o
	rm -f HexToBin HexToBin.o
	rm -f Cezar Cezar.o
