FindMin: FindMin.o
	ld -o FindMin FindMin.o
FindMin.o: FindMin.s
	as -o FindMin.o FindMin.s
FindMax: FindMax.o
	ld -o FindMax FindMax.o
FindMax.o: FindMax.s
	as -o FindMax.o FindMax.s
clean:
	rm -f FindMin FindMin.o	
	rm -f FindMax FindMax.o
