HelloWorld64: HelloWorld64.o
	ld -o HelloWorld64 HelloWorld64.o
HelloWorld64.o: HelloWorld64.s
	as -o HelloWorld64.o HelloWorld64.s
HelloWorld32: HelloWorld32.o
	ld -o HelloWorld32 HelloWorld32.o
HelloWorld32.o: HelloWorld32.s
	as -o HelloWorld32.o HelloWorld32.s
Input64: Input64.o
	ld -o Input64 Input64.o
Input64.o: Input64.s
	as -o Input64.o Input64.s
Input32: Input32.o
	ld -o Input32 Input32.o
Input32.o: Input32.s
	as -o Input32.o Input32.s
