HelloWorld64: HelloWorld64.o
	ld -o HelloWorld64 HelloWorld64.o
HelloWorld64.o: HelloWorld64.s
	as -o HelloWorld64.o HelloWorld64.s
HelloWorld32: HelloWorld32.o
	ld -o HelloWorld32 HelloWorld32.o
HelloWorld32.o: HelloWorld32.s
	as -o HelloWorld32.o HelloWorld32.s
