Fib: Fib.o
	ld -o Fib Fib.o
Fib.o: Fib.s
	as -o Fib.o -gstabs Fib.s
E4: E4.o
	ld -o E4 E4.o
E4.o: E4.s
	as -o E4.o -gstabs E4.s
E5: E5.o
	ld -o E5 E5.o
E5.o: E5.s
	as -o E5.o -gstabs E5.s
E6: E6.o
	ld -o E6 E6.o
E6.o: E6.s
	as -o E6.o -gstabs E6.s
clean:
	rm -f Fib Fib.o
	rm -f E4 E4.o
	rm -f E5 E5.o
	rm -f E6 E6.o
